---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.bytetrade.io
  resources:
  - applicationmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.bytetrade.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.bytetrade.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - app.bytetrade.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sys.bytetrade.io
  resources:
  - appenvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sys.bytetrade.io
  resources:
  - appenvs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sys.bytetrade.io
  resources:
  - systemenvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sys.bytetrade.io
  resources:
  - systemenvs/status
  verbs:
  - get
  - patch
  - update
