name: Build the release
on:
  push:
    branches:
      - "main"
    tags:
      - "*"
jobs:
  build0-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: get latest tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: get-latest-tag
        with:
          fallback: latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: beclab/app-service:${{ steps.get-latest-tag.outputs.tag }}
          file: Dockerfile