name: Build the main branch
on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build0-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.6'
      - run: make build
