name: Build the main branch
on: 
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
    branches:
      - "main"
      - "release-*"
jobs:
  build0-main:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y btrfs-progs libbtrfs-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.6'
      - run: make build
